# Aplicação
server.port: 8080
time:
    expiration:
        # Em minutos (5)
        access-token: 1
        # Em horas (48)
        refresh-token: 48
spring:
    application.name: Sli

# Database global configuration
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: neoneo4j
logging:
    level:
        org:
            springframework:
                data:
                    neo4j: DEBUG

# Chave secreta para tokens JWT
jwt:
    asym-key:
        private: classpath:app.key
        public: classpath:app.pub
    sym-key: classpath:sim256.key
